build: resolve npm compile errors
Got rid of webworker dependency, which is incompatible
with current types definitions:

```
node_modules/@types/node/globals.d.ts:114:13 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'AbortSignal' must be of type '{ new (): AbortSignal; prototype: AbortSignal; abort(reason?: any): AbortSignal; }', but here has type '{ new (): AbortSignal; prototype: AbortSignal; }'.

114 declare var AbortSignal: {
                ~~~~~~~~~~~

  node_modules/typescript/lib/lib.webworker.d.ts:751:13
    751 declare var AbortSignal: {
                    ~~~~~~~~~~~
    'AbortSignal' was also declared here.

Found 1 error in node_modules/@types/node/globals.d.ts:114

```